api_branch : origin/master
api_parser : ~
api_cfgmod : clone
api_runner : ~
api_paths  : lib
env_make   : ~
env_prep   : get-composer
env_post   : ci-coveralls,ci-codacy
php_conf   : timezone
php_exts   : igbinary
app_prep   : dep-composer
app_post   : ~
app_path   : ~
pkg_name   : augustus-serializer-library
pkg_desc   : "simple abstraction on serialize functions with support for php- json- and igbinary-based serialization"
pkg_bndl   : false
