api_branch: origin/master
api_parser: ~
api_cfgmod: clone
api_runner: ~
api_paths: lib
env_make: ~
env_prep: composer-get
php_conf: timezone
php_exts: igbinary
app_prep: composer-req
app_post: ~
env_post: composer-del,ci-coveralls,ci-codacy
app_path: ~
pkg_name: augustus-serializer-library
pkg_desc: "A simple serialization abstraction with support for php- json- and igbinary-based serialization."
pkg_bndl: false
